# Generated by Django 3.1.6 on 2021-05-25 06:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('parent_id', models.IntegerField(db_index=True, null=True, verbose_name='Родитель')),
                ('category', models.CharField(choices=[('О', 'область'), ('Р', 'район'), ('М', 'місто'), ('Т', 'смт'), ('С', 'село'), ('Щ', 'селище')], max_length=1, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
    ]
