# Generated by Django 3.2.1 on 2021-05-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210525_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Запись активна?'),
        ),
    ]
