# Generated by Django 3.2.1 on 2021-06-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210601_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='parent_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Родитель'),
        ),
    ]
