# Generated by Django 3.2.1 on 2021-06-01 21:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_place_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('О', 'ОБЛАСТЬ '), ('Р', 'РАЙОН '), ('М', 'м. '), ('Т', 'смт. '), ('С', 'с. '), ('Щ', 'с. ')], max_length=1, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
    ]
