# Generated by Django 3.1.6 on 2021-06-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210601_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('О', 'обл. '), ('РГ', 'р-н '), ('РН', 'р-н '), ('М', 'м. '), ('Т', 'смт. '), ('С', 'с. '), ('Щ', 'с. ')], max_length=2, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_location',
            field=models.BooleanField(default=False, verbose_name='Это НП?'),
        ),
    ]
